### ISSUE TITLE
We need to Improve Appearance of our Service

### ISSUE THREAD

**Issue by davin111** [swsnu/swpp2019-team3#141]
**Is your feature request related to a problem? Please describe.**
We should improve appearance of our service.

**Describe the solution you'd like**
Think about visual design, UI, and UX more. Then do CSS or related works.

**Additional context**
This is important in that some distortion of certain pages on certain conditions make users distracted and uncomfortable.

**Comment by njsh4261** [comment]
Here are the list of works regarding design that comes in my mind for now (there should be more works):

- The content should be centered, so that our site would attract the user's attention better.
- Adjust the location of buttons on overall components. Some buttons are not placed appropriately, which makes our site less prettier.
- Improve button design. It would be better if some buttons have changes on view when hovering them. Also we can improve 'like/unlike' button better.
- Add CSS files to modals which does not have corresponding of it. Most of them are related to collection management.

Some of them are done in #184.
