### ISSUE TITLE
The number of likes on ReviewCard does not change when clicking the button

### ISSUE THREAD

**Issue by njsh4261** [swsnu/swpp2019-team3#46]
**Describe the bug**
--
Currently, 'the number of likes button' on ReviewCard(the left number button) component does not change for clicking it.

**To Reproduce**
--
1. Start React server, then go to '/main' or '/profile/:id' page
2. Click the left number button on any Review
3. The number won't change, you see the error.

**Expected behavior**
--
The number should be increased or decresed by 1.
It does not matter whether it is connected to reducer or not.

**Screenshots**
--

**Additional context**
--
It may be good to be solved before mid presentation on the first week of November, with connecting the component to Redux things.
If works on Redux is not possible until mid presentation, please at least modify it to merely change the number for live demo.

**Comment by davin111** [comment]
Actually, it is about not only ReviewCard, but also PaperCard. And I think it is not a problem. Because as you can see, PaperCard and ReviewCard have their own 'state' likeCount and also have 'props'(which are gotten from the containers importing the cards) likeCount.

Because we didn't implement reducers and states related with 'like' features, I knew about it but let them be. Since I couldn't know exactly how they would be implemented, I just made they reflect 'props' likeCount when I touched them. (Actually CollectionCard should have the same symptoms, but mistakenly it reflect its 'state' likeCount for now.)

I expect when we implement reducers related with each objects(papers, collections, and reviews). I think they couldn't be fixed and also don't need to be fixed until that time. Surely, it should be soon.

**Comment by njsh4261** [comment]
Yes I understand that we actually don't need to fix this before implementing redux for them, I was just worried about mid presentation. For now the number of likes on CollectionCard does change, but the one on ReviewCard not. It is a tiny problem, but I guess if we don't notice this issue then our audience may wonder.

**Comment by davin111** [comment]
> Yes I understand that we actually don't need to fix this before implementing redux for them, I was just worried about mid presentation. For now the number of likes on CollectionCard does change, but the one on ReviewCard not. It is a tiny problem, but I guess if we don't notice this issue then our audience may wonder.

@njsh4261 Good point, thanks!
